### PR TITLE
Allow array value comparison for 'equal' and 'not_equal' xml translation rules

### PR DESCRIPTION
**Pull request by elohanlon**

### CODE REVIEW

**Comment by barmintor** [comment]
Do I understand correctly that HUG is requesting that equal_to(val) act like a reversed version of `include?`

**Comment by elohanlon** [comment]
@barmintor `equal` acts like a regular version of `include` (does array contain) and `not_equal` is like a reversed version (does array NOT contain).

does value equal [ANY OF THESE]
and
does value not_equal [ANY OF THESE]

**Comment by barmintor** [comment]
I have some mixed feelings. Overloading `equal_to` this way (obviously) works, but creates a knowledge/documentation need. My instinct is that new comparison functions would be preferable (any_of/not_any_of), but that would be a lot more work (not just the addition, but type checking the value_to_compare_to.

**Comment by barmintor** [comment]
The work looks otherwise perfectly good, so my only question is whether you worry that hiding two behaviors in one function is going to generate bugs down the line. I don't think value_for_field_name will ever return an array, but if it did this would become a complicated thing to explain.

**Comment by elohanlon** [comment]
@barmintor You make good points.  I just pushed an updated commit with `equals_any_of` and `equals_none_of` instead.  What do you think?

I've also applied these changes to Hyacinth 3, but haven't pushed yet.

**Comment by elohanlon** [comment]
Thanks for the helpful feedback!

**Pull request merged**
