### PR TITLE
HYACINTH-934, HYACINTH-937, and HYACINTH-936

### PR DESCRIPTION
**Pull request by elohanlon**
HYACINTH-934 (Search button should always forces result refresh)
HYACINTH-937 (Add a clear search button that clears search parameters)
HYACINTH-936 (DisplayField component should show new lines and other text spacing)

### CODE REVIEW

**Comment by JackBlackLight** [comment]
The code changes are clear and look good. I tested the fixes through the user interface and the search related fixes work, but the text area issue remains. I tried it three browsers. In chrome and firefox, the text did not wrap at all. In safari, the text wrapped, but the breaks happened in the middle of words, slicing off a last letter and placing it on the next line.

**Comment by elohanlon** [comment]
@JackBlackLight Good catch, thanks!  HYACINTH-936 was supposed to fix the issue of new line characters not being rendered as new lines in show mode, but I should have used "pre-wrap" instead of "pre" to allow for line wrapping.  Fixed now!

**Review by JackBlackLight — APPROVED** [review]
Looks great/works great @elohanlon !

**Comment by elohanlon** [comment]
Thanks, @JackBlackLight !

**Pull request merged**
