### PR TITLE
Adding graphql endpoint

### PR DESCRIPTION
**Pull request by cgalarza**
Accepts queries for users, user, authenticatedUser and mutations for createuser and updateuser

This implements most of the features of our /users REST endpoint. I still have to port over the test, but I want to get this out there so you guys can get a sense for it. This is by far one of our more complicated REST endpoints.

### CODE REVIEW

**Comment by cgalarza** [comment]
@barmintor and @elohanlon would you guys like to look at this before I merge?

**Comment by barmintor** [comment]
👻

**Comment by cgalarza** [comment]
> 👻

I laughed really hard when I saw this!

**Comment by elohanlon** [comment]
Beat me to the merge, but 👍 from me!

**Pull request merged**
