### PR TITLE
Adding .ruby-version and .ruby-gemset to gitignore list for repository.

### PR DESCRIPTION
**Pull request by cgalarza**

### CODE REVIEW

**Comment by cgalarza** [comment]
@elohanlon Could we remove some of the editor-specific gitignore'd files?

**Comment by elohanlon** [comment]
@cgalarza I don't mind if we get rid of these:

```
# Ignore application project files
*.komodoproject

# Ignore elo2112-specific
reference-files/*
```

But I'd like to keep these just in case any Hyacinth contributor ever forgot to add these to their local machine's global ignores:
```
# Ignore editor files
*~
\#*\#
```

**Comment by cgalarza** [comment]
That sounds good. 

What about this one?
```
# Ignore local Guardfile customation file
 config/local_guardfile_customizations.yml
```

**Comment by elohanlon** [comment]
@cgalarza Oh yeah, definitely want that one to go.  I'm sure I accidentally copied that in from an earlier project's .gitignore file a VERY long time ago.

**Comment by cgalarza** [comment]
@elohanlon pushed changes

**Pull request merged**
